# Generated by Django 5.2.1 on 2026-03-08 09:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_file_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('risk_level', models.CharField(choices=[('healthy', 'Healthy'), ('medium', 'Medium Risk'), ('high', 'High Risk')], default='healthy', max_length=20)),
                ('negative_sentiment_pct', models.FloatField(default=0.0)),
                ('delay_count', models.IntegerField(default=0)),
                ('is_silent', models.BooleanField(default=False)),
                ('message_count', models.IntegerField(default=0)),
                ('signals', models.JSONField(default=list)),
                ('window_hours', models.IntegerField(default=72)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_snapshots', to='core.project')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project', '-created_at'], name='core_risksn_project_8a92ed_idx')],
            },
        ),
    ]
