# Generated by Django 5.2.1 on 2026-09-02 05:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_risksnapshot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Auto-generated if blank', max_length=255)),
                ('meeting_date', models.DateField(blank=True, help_text='Extracted from transcript or set by PM', null=True)),
                ('transcript_text', models.TextField()),
                ('raw_ai_json', models.JSONField(blank=True, help_text='Raw GPT-4 response for debugging', null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Extraction'), ('EXTRACTING', 'Extracting...'), ('DRAFT', 'Draft – Awaiting Review'), ('APPROVED', 'Approved'), ('PUSHED', 'Pushed to Procore'), ('FAILED', 'Extraction Failed')], default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Populated if extraction fails')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='core.project')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_meetings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('made_by_raw_name', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('made_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decisions_made', to='core.projectcontact')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='core.meetingrecord')),
            ],
        ),
        migrations.CreateModel(
            name='Blocker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('blocking_who', models.CharField(blank=True, max_length=255)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=10)),
                ('resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blockers', to='core.meetingrecord')),
            ],
            options={
                'ordering': ['-severity', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_description', models.TextField()),
                ('owner_raw_name', models.CharField(blank=True, help_text='Name as it appeared in transcript', max_length=100)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('DONE', 'Done'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=20)),
                ('procore_record_id', models.CharField(blank=True, help_text='Procore ID after push', max_length=100)),
                ('notified_at', models.DateTimeField(blank=True, help_text='When WhatsApp notification was sent', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(blank=True, help_text='Resolved from transcript name → project contact', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_items', to='core.projectcontact')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_items', to='core.meetingrecord')),
            ],
            options={
                'ordering': ['due_date', 'created_at'],
            },
        ),
    ]
