# Generated by Django 5.2.1 on 2026-09-04 10:08

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_meetingrecord_decision_blocker_actionitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcoreCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', core.models.EncryptedField()),
                ('client_secret', core.models.EncryptedField()),
                ('company_id', models.CharField(max_length=50)),
                ('procore_project_id', models.CharField(max_length=50)),
                ('environment', models.CharField(choices=[('sandbox', 'Sandbox (Testing)'), ('production', 'Production (Live)')], default='sandbox', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='procore_credential', to='core.project')),
            ],
            options={
                'verbose_name': 'Procore Credential',
            },
        ),
    ]
