# Generated by Django 5.2.1 on 2026-09-04 14:30

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_procorecredential'),
    ]

    operations = [
        migrations.AddField(
            model_name='procorecredential',
            name='access_token',
            field=core.models.EncryptedField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='procorecredential',
            name='is_connected',
            field=models.BooleanField(default=False, help_text='True after successful OAuth authorization'),
        ),
        migrations.AddField(
            model_name='procorecredential',
            name='refresh_token',
            field=core.models.EncryptedField(blank=True, default=''),
        ),
    ]
