# Generated by Django 5.2.1 on 2026-09-04 21:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_procorecredential_access_token_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcoreMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('mock', 'Mock (local testing)'), ('sandbox', 'Sandbox (Procore testing)'), ('production', 'Production (live)')], default='mock', max_length=20)),
                ('mock_base_url', models.CharField(default='http://localhost:8000/mock-procore', help_text='Base URL for mock Procore endpoints', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Procore Mode',
            },
        ),
    ]
